sudo: required
dist: trusty

language: node_js
node_js:
  - "8"

script: npm run build

deploy:
  target-branch: master
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: build
  on:
    branch: dev

notifications:
  email: false
